<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    // 1、原始写法
    new Promise((resolve,reject) => {
      setTimeout(() => {
        resolve('111')
      }, 1000);
    }).then(res => {
      console.log(res);
      // 当Promise()函数中只有resolve的时候,可以省略reject不写
      return new Promise((resolve,reject) => {
        resolve(res + '222')
      })
    }).then(res => {
      console.log(res);
      return new Promise(resolve =>{
        resolve(res + '333')
      })
    }).then(res => {
      console.log(res);
      console.log('----------分隔线----------分隔线-------------分隔线-----------');
    })

    // 2、简写一：
    new Promise((resolve,reject) => {
      setTimeout(() => {
        resolve('111')
      }, 1000);
    }).then(res => {
      console.log(res);
      // 当Promise()函数中只有resolve的时候,还可以更进一步简写
      return new Promise(resolve => {
        resolve(res + '222')
      })
    }).then(res => {
      console.log(res);
      return new Promise(resolve =>{
        resolve(res + '333')
      })
    }).then(res => {
      console.log(res);
      console.log('----------分隔线----------分隔线-------------分隔线-----------');
    })

    // 3、简写二：
    new Promise((resolve,reject) => {
      setTimeout(() => {
        resolve('111')
      }, 1000);
    }).then(res => {
      console.log(res);
      return Promise.resolve(res + '222')
    }).then(res => {
      console.log(res);
      return Promise.resolve(res + '333')
    }).then(res => {
      console.log(res);
      console.log('----------分隔线----------分隔线-------------分隔线-----------');
    })

    // 4、简写三：
    new Promise((resolve,reject) => {
      setTimeout(() => {
        resolve('111')
      }, 1000);
    }).then(res => {
      console.log(res);
      return res + '222'
    }).then(res => {
      console.log(res);
      return res + '333'
    }).then(res => {
      console.log(res);
      console.log('----------分隔线----------分隔线-------------分隔线-----------');
    })

    // 5、请求失败时,reject的简写
    new Promise((resolve,reject) => {
      setTimeout(() => {
        resolve('111')
      }, 1000);
    }).then(res => {
      console.log(res);
      // return Promise.reject('出错了！！！' + res)
      // 请求失败时,还可以写成：
      throw '出错啦！！！' + res
    }).then(res => {
      console.log(res);
      return res + '333'
    }).then(res => {
      console.log(res);
    }).catch(err =>{
      console.log('catch块：' + err);
    })
  </script>
</body>
</html>